Fix/update database initialization
magdalenagola/virtual-stylist pull request #25
Opened 2020-05-29 15:52 UTC by szczepanTopolski

2020-05-29 16:07 UTC, magdalenagola requested changes

2020-05-29 16:07 UTC, magdalenagola commented on src/main/java/com/codecool/virtualstylist/wardrobe/DbInitClothes.java
> +        Cloth cloth2 = new Cloth("dx", ClothesProperties.BodyPart.CHEST, ClothesProperties.ClothType.JEANS, ClothesProperties.Color.RED,"xd","xd", ClothesProperties.Style.BOHO,"xd", ClothesProperties
please use more proper arguments

2020-05-30 10:27 UTC, szczepanTopolski commented on src/main/java/com/codecool/virtualstylist/wardrobe/DbInitClothes.java
> +        Cloth cloth1 = new Cloth("xd", ClothesProperties.BodyPart.CHEST, ClothesProperties.ClothType.JEANS, ClothesProperties.Color.RED,"xd","xd", ClothesProperties.Style.BOHO,"xd", ClothesProperties
```suggestion
        Cloth cloth1 = new Cloth("/path.jpg", ClothesProperties.BodyPart.CHEST, ClothesProperties.ClothType.BLOUSE, ClothesProperties.Color.RED,"234","Zara", ClothesProperties.Style.BOHO,"#FavBlouse", ClothesProperties.Size.S,true,"zara.com",adam);
```

2020-05-30 10:29 UTC, szczepanTopolski commented on src/main/java/com/codecool/virtualstylist/wardrobe/DbInitClothes.java
> +        Cloth cloth2 = new Cloth("dx", ClothesProperties.BodyPart.CHEST, ClothesProperties.ClothType.JEANS, ClothesProperties.Color.RED,"xd","xd", ClothesProperties.Style.BOHO,"xd", ClothesProperties
```suggestion
        Cloth cloth2 = new Cloth("/path2.jpg", ClothesProperties.BodyPart.LEGS, ClothesProperties.ClothType.JEANS, ClothesProperties.Color.RED,"543","Zara", ClothesProperties.Style.BOHO,"#FavJeans", ClothesProperties.Size.S,true,"zara.com",adam);
```

2020-05-30 10:46 UTC, magdalenagola approved these changes

2020-05-30 10:46 UTC, merged